# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
       name: 'Default'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
       containerRegistry: 'nitinlal99-docker-hub'
       repository: 'nitinlal99/setting-currency-exchange-devops'
              command: 'buildandpush'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          '$(tag)'
- task: Docker@2
  inputs:
    containerRegistry: 'nitinlal99-docker-hub'
    repository: 'nitinlal99/setting-currency-exchange-devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
