# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: 'Default'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - powershell: echo Build FirstJob
    - powershell: echo $(PipelineLevelVariable)
    - powershell: echo $(Build.BuildNumber)
    - powershell: echo $(Build.BuildId)
    - powershell: echo $(Build.SourceBranchName)
    - powershell: echo $(Build.SourcesDirectory)
    - powershell: echo $(System.DefaultWorkingDirectory)
    - powershell: ls -R $(System.DefaultWorkingDirectory)
    - powershell: echo $(Build.ArtifactStagingDirectory)
    - powershell: java -version
    - powershell: node --version
    - powershell: python --version 
    - powershell: mvn -version 
    - powershell: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - powershell: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
  # - job: SecondJob
  #   steps:
  #   - powershell: echo Build SecondJob
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - powershell: echo $(environment)DeployJob
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#     - powershell: echo $(environment)DeployJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - powershell: echo ProdDeployJob